spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_scheduler
    username: root
    password: root
    poolSize: 2
    timeout: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
data:
    jdbc:
      repositories:
        enabled: false    